# Generated by Django 3.1.5 on 2021-01-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=300)),
                ('date_since', models.DateField(verbose_name='początek subskrypcji')),
                ('interest1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scraper.institution')),
                ('interest2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scraper.institution')),
                ('interest3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scraper.institution')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000)),
                ('content', models.CharField(max_length=3000)),
                ('type', models.CharField(max_length=400, null=True)),
                ('date_added', models.DateField(verbose_name='data dodania')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraper.institution')),
            ],
        ),
    ]
